---
# defaults file for kvm_provision
#
base_image_name: /home/jlmanrique/RedHat/images/rhel-8.5-update-2-x86_64-kvm.qcow2
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: f34-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: default
vm_root_pass: test123
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub
